import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import ReactQueryProvider from './ReactQueryProvider'
import FetchUser from './FetchUser'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <FetchUser />

      <ReactQueryProvider>
        <body className={inter.className}>
          <Toaster toastOptions={{ className: '!text-black-75 !rounded-[16px]' }} />
          {children}
        </body>
      </ReactQueryProvider>
    </html>
  )
}
